// streets.json / regions.json → seeds/seed.sql (PLAN.MD §1.2).
// Emits INSERT OR IGNORE so re-running against a seeded DB is a no-op.
// Apply with: wrangler d1 execute cityshield-db --local|--remote --file=seeds/seed.sql

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));

function loadList(file) {
  const data = JSON.parse(readFileSync(join(here, file), "utf8"));
  if (!Array.isArray(data)) throw new Error(`${file}: expected a JSON array`);
  return [...new Set(data.filter((x) => typeof x === "string" && x.trim()))];
}

const esc = (s) => `'${s.replace(/'/g, "''")}'`;

function insertBatches(table, column, values, batchSize = 100) {
  const lines = [];
  for (let i = 0; i < values.length; i += batchSize) {
    const rows = values.slice(i, i + batchSize).map((v) => `(${esc(v)})`);
    lines.push(`INSERT OR IGNORE INTO ${table} (${column}) VALUES\n${rows.join(",\n")};`);
  }
  return lines.join("\n");
}

const regions = loadList("regions.json");
const streets = loadList("streets.json");

const sql = [
  "-- Generated by seeds/generate-seed.mjs — do not edit by hand.",
  insertBatches("regions", "region_name", regions),
  insertBatches("streets", "street_name", streets),
  "",
].join("\n");

writeFileSync(join(here, "seed.sql"), sql, "utf8");
console.log(`seed.sql written: ${regions.length} regions, ${streets.length} streets`);
