// streets.json / regions.json → seeds/seed.sql (SPEC.md §1.2).
//
// Entries are either a bare name (the original hand-maintained form) or
// { name, lat, lng } as written by tools/osm-seed-builder. Both are accepted so
// a partially migrated seed file still generates.
//
// Emits an upsert rather than INSERT OR IGNORE: re-running must stay a no-op on
// an already-seeded DB, but it must ALSO be able to backfill coordinates onto
// rows that were seeded before they had any. COALESCE keeps that one-way —
// an entry without coordinates never blanks out coordinates already in the DB.
//
// Apply with: wrangler d1 execute cityshield-db --local|--remote --file=seeds/seed.sql
//
// Reads this directory and writes seed.sql beside the JSON by default. Both are
// overridable so tools/osm-seed-builder can generate SQL from its own output
// directory without touching backend/seeds — one implementation of the upsert,
// two sets of inputs:
//
//   node seeds/generate-seed.mjs --in ../tools/osm-seed-builder/output

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));

function flag(name, fallback) {
  const i = process.argv.indexOf(name);
  const value = i === -1 ? undefined : process.argv[i + 1];
  return value && !value.startsWith("--") ? resolve(value) : fallback;
}

const inDir = flag("--in", here);
const outFile = flag("--out", join(inDir, "seed.sql"));

function loadEntries(file) {
  const data = JSON.parse(readFileSync(join(inDir, file), "utf8"));
  if (!Array.isArray(data)) throw new Error(`${file}: expected a JSON array`);

  // Last entry wins on a duplicate name, so a later row carrying coordinates
  // supersedes an earlier bare one.
  const byName = new Map();
  for (const item of data) {
    const name = (typeof item === "string" ? item : item?.name ?? "").trim();
    if (!name) continue;
    const lat = typeof item === "object" ? item.lat : null;
    const lng = typeof item === "object" ? item.lng : null;
    const hasCoords = Number.isFinite(lat) && Number.isFinite(lng);
    byName.set(name, { name, lat: hasCoords ? lat : null, lng: hasCoords ? lng : null });
  }
  return [...byName.values()].sort((a, b) => a.name.localeCompare(b.name));
}

const esc = (s) => `'${s.replace(/'/g, "''")}'`;
const num = (n) => (n === null ? "NULL" : String(n));

/**
 * Alternative written forms for a region, as `[{ alias, region }]`.
 *
 * Optional: a seed directory written by an older tool run has no aliases.json,
 * and the file is not part of what tools/osm-seed-builder extracts.
 */
function loadAliases() {
  let data;
  try {
    data = JSON.parse(readFileSync(join(inDir, "aliases.json"), "utf8"));
  } catch (e) {
    if (e.code === "ENOENT") return [];
    throw e;
  }
  if (!Array.isArray(data)) throw new Error("aliases.json: expected a JSON array");

  const byAlias = new Map();
  for (const item of data) {
    const alias = (item?.alias ?? "").trim();
    const region = (item?.region ?? "").trim();
    if (alias && region) byAlias.set(alias, { alias, region });
  }
  return [...byAlias.values()].sort((a, b) => a.alias.localeCompare(b.alias));
}

/**
 * Aliases are keyed to their region by NAME, not by id — region ids are
 * autoincrement and differ between the local and the remote database, so a
 * literal id in a checked-in seed file would be wrong on one of them. The
 * SELECT resolves it at apply time and inserts nothing if the region is
 * missing, which is also what makes re-applying safe.
 */
function insertAliases(entries) {
  return entries.map((e) =>
    `INSERT INTO region_aliases (alias, region_id)\n` +
    `SELECT ${esc(e.alias)}, id FROM regions WHERE region_name = ${esc(e.region)}\n` +
    `ON CONFLICT(alias) DO UPDATE SET region_id = excluded.region_id;`,
  ).join("\n");
}

function insertBatches(table, column, entries, batchSize = 100) {
  const lines = [];
  for (let i = 0; i < entries.length; i += batchSize) {
    const rows = entries
      .slice(i, i + batchSize)
      .map((e) => `(${esc(e.name)}, ${num(e.lat)}, ${num(e.lng)})`);
    lines.push(
      `INSERT INTO ${table} (${column}, lat, lng) VALUES\n${rows.join(",\n")}\n` +
        `ON CONFLICT(${column}) DO UPDATE SET\n` +
        `  lat = COALESCE(excluded.lat, ${table}.lat),\n` +
        `  lng = COALESCE(excluded.lng, ${table}.lng);`,
    );
  }
  return lines.join("\n");
}

const regions = loadEntries("regions.json");
const streets = loadEntries("streets.json");
const aliases = loadAliases();

const sql = [
  "-- Generated by seeds/generate-seed.mjs — do not edit by hand.",
  insertBatches("regions", "region_name", regions),
  insertBatches("streets", "street_name", streets),
  // After the regions, whose rows the SELECT below has to find.
  ...(aliases.length > 0 ? [insertAliases(aliases)] : []),
  "",
].join("\n");

writeFileSync(outFile, sql, "utf8");

const withCoords = (entries) => entries.filter((e) => e.lat !== null).length;
console.log(
  `${outFile} written: ${regions.length} regions (${withCoords(regions)} with coordinates), ` +
    `${streets.length} streets (${withCoords(streets)} with coordinates), ` +
    `${aliases.length} region aliases`,
);
