<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.23" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.23" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="Testcontainers.PostgreSql" Version="4.1.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CityShieldAPI\CityShieldAPI.csproj" />
    <ProjectReference Include="..\CityShieldAPI.Core\CityShieldAPI.Core.csproj" />
    <ProjectReference Include="..\CityShieldAPI.Common\CityShieldAPI.Common.csproj" />
    <ProjectReference Include="..\CityShieldAPI.Data\CityShieldAPI.Data.csproj" />
    <ProjectReference Include="..\CityShieldAPI.Data.Models\CityShieldAPI.Data.Models.csproj" />
    <ProjectReference Include="..\CityShieldAPI.DTOs\CityShieldAPI.DTOs.csproj" />
  </ItemGroup>

</Project>
